from django.db import models

class food(models.Model):
    """ 食材テーブル """
    food_id = models.CharField("食材ID", primary_key=True, null=False, max_length=10)
    food_name_1 = models.CharField("食材名1", null=True, max_length=256)
    food_category_1 = models.CharField("＜類＞", null=True, max_length=50)
    food_category_2 = models.CharField("（類）", null=True, max_length=50)
    food_category_3 = models.CharField("[類]", null=True, max_length=50)
    food_category_4 = models.CharField("名前(部位、種類)", null=True, max_length=50)
    food_status = models.CharField("状態", null=True, max_length=50)
    food_picture = models.TextField("食材写真", null=True,)
    create_user = models.CharField("作成者", null=False, max_length=128)
    create_datetime = models.DateTimeField(("作成日"), auto_now=False, auto_now_add=True)
    update_user = models.CharField("更新者", max_length=128)
    update_datetime = models.DateTimeField(("更新日"), auto_now=True, auto_now_add=False)

class food_jfsil_relations(models.Model):
    """ 食材テーブルと日本食品標準成分表2015年版（七訂）テーブルの対応付け """
    food_id = models.ForeignKey("food", primary_key=True, on_delete=models.PROTECT)
    INDEX_NUM = models.CharField("索引番号", blank=False, max_length=10)

class five_nutrients(models.Model):
    """ 五大栄養素テーブル """
    food_id = models.OneToOneField(food, related_name='nutrients_five', primary_key=True, on_delete=models.PROTECT)
    food_name = models.CharField("食材名", null=False, max_length=256)
    food_group = models.IntegerField("食品群", null=False)
    energy_kcal = models.IntegerField("エネルギー（kcal）", null=False)
    energy_kj = models.IntegerField("エネルギー（kJ）", null=False)
    protain = models.DecimalField("たんぱく質", null=False, max_digits=10, decimal_places=2)
    fat = models.DecimalField("脂質", null=False, max_digits=10, decimal_places=2)
    carbohydrates = models.DecimalField("炭水化物", null=False, max_digits=10, decimal_places=2)
    mineral_Na = models.DecimalField("ナトリウム", null=False, max_digits=10, decimal_places=2)
    mineral_Ka = models.DecimalField("カリウム", null=False, max_digits=10, decimal_places=2)
    mineral_Ca = models.DecimalField("カルシウム", null=False, max_digits=10, decimal_places=2)
    mineral_P = models.DecimalField("リン", null=False, max_digits=10, decimal_places=2)
    mineral_Fe = models.DecimalField("鉄", null=False, max_digits=10, decimal_places=2)
    vitamin_A = models.DecimalField("ビタミンA", null=False, max_digits=10, decimal_places=2)
    vitamin_B1 = models.DecimalField("ビタミンB1", null=False, max_digits=10, decimal_places=2)
    vitamin_B2 = models.DecimalField("ビタミンB2", null=False, max_digits=10, decimal_places=2)
    vitamin_Niacin = models.DecimalField("ナイアシン", null=False, max_digits=10, decimal_places=2)
    vitamin_C = models.DecimalField("ビタミンC", null=False, max_digits=10, decimal_places=2)
    NaCl_EQ = models.DecimalField("食塩相当量", null=False, max_digits=10, decimal_places=2)
    fibtg = models.DecimalField("食物繊維", null=False, max_digits=10, decimal_places=2)
    cholesterol = models.DecimalField("コレステロール", null=False, max_digits=10, decimal_places=2)
    create_user = models.CharField("作成者", null=False, max_length=128)
    create_datetime = models.DateTimeField(("作成日"), auto_now=False, auto_now_add=True)
    update_user = models.CharField("更新者", max_length=128)
    update_datetime = models.DateTimeField(("更新日"), auto_now=True, auto_now_add=False)

class nutrients_list(models.Model):
    """ 栄養素一覧テーブル """
    nutrients_id = models.CharField("栄養素ID", primary_key=True, null=False, max_length=10)
    nutrients_name = models.CharField("栄養素名", null=False, max_length=30)
    nutrients_unit = models.CharField("単位", null=False, max_length=10)
    
class food_tags(models.Model):
    """ 食材タグテーブル """
    food_id = models.ForeignKey("food", primary_key=True, on_delete=models.PROTECT)
    tag_id = models.ForeignKey("tag_list", on_delete=models.PROTECT)

class tag_list(models.Model):
    """ タグ一覧テーブル """
    tag_id = models.CharField("タグID", primary_key=True, null=False, max_length=10)
    tag_name = models.CharField("タグ名", null=False, max_length=50)

class japanese_food_standard_ingredients_list(models.Model):
    """ 日本食品標準成分表2015年版（七訂）テーブル """
    FOOD_GROUP = models.IntegerField("食品群", null=False)
    FOOD_NUM = models.IntegerField("食品番号", null=False)
    INDEX_NUM = models.IntegerField("索引番号", primary_key=True, null=False)
    Tagnames = models.CharField("食品名", null=False, max_length=256)
    REFUSE = models.IntegerField("廃棄率", null=False)
    ENERC_KCAL = models.IntegerField("エネルギー（kcal）", null=False)
    ENERC = models.IntegerField("エネルギー（kJ）", null=False)
    WATER = models.DecimalField("水分", null=False, max_digits=10, decimal_places=2)
    PROTAIN = models.DecimalField("たんぱく質", null=False, max_digits=10, decimal_places=2)
    PROTCAA = models.DecimalField("アミノ酸組成によるたんぱく質", null=False, max_digits=10, decimal_places=2)
    FAT = models.DecimalField("脂質", null=False, max_digits=10, decimal_places=2)
    FATNLEA = models.DecimalField("トリアシルグリセロール当量", null=False, max_digits=10, decimal_places=2)
    FASAT = models.DecimalField("飽和脂肪酸", null=False, max_digits=10, decimal_places=2)
    FAMS = models.DecimalField("一価不飽和脂肪酸", null=False, max_digits=10, decimal_places=2)
    FAPU = models.DecimalField("多価不飽和脂肪酸", null=False, max_digits=10, decimal_places=2)
    CHOLE = models.DecimalField("コレステロール", null=False, max_digits=10, decimal_places=2)
    CARBOHYDRATES = models.DecimalField("炭水化物", null=False, max_digits=10, decimal_places=2)
    CHOAVLM = models.DecimalField("利用可能炭水化物（単糖当量）", null=False, max_digits=10, decimal_places=2)
    FIBSOL = models.DecimalField("水溶性食物繊維", null=False, max_digits=10, decimal_places=2)
    FIBINS = models.DecimalField("不溶性食物繊維", null=False, max_digits=10, decimal_places=2)
    FIBTG = models.DecimalField("食物繊維総量", null=False, max_digits=10, decimal_places=2)
    ASH = models.DecimalField("灰分", null=False, max_digits=10, decimal_places=2)
    NA = models.DecimalField("ナトリウム", null=False, max_digits=10, decimal_places=2)
    K = models.DecimalField("カリウム", null=False, max_digits=10, decimal_places=2)
    CA = models.DecimalField("カルシウム", null=False, max_digits=10, decimal_places=2)
    MG = models.DecimalField("マグネシウム", null=False, max_digits=10, decimal_places=2)
    P = models.DecimalField("リン", null=False, max_digits=10, decimal_places=2)
    FE = models.DecimalField("鉄", null=False, max_digits=10, decimal_places=2)
    ZN = models.DecimalField("亜鉛", null=False, max_digits=10, decimal_places=2)
    CU = models.DecimalField("銅", null=False, max_digits=10, decimal_places=2)
    MN = models.DecimalField("マンガン", null=False, max_digits=10, decimal_places=2)
    ID = models.DecimalField("ヨウ素", null=False, max_digits=10, decimal_places=2)
    SE = models.DecimalField("セレン", null=False, max_digits=10, decimal_places=2)
    CR = models.DecimalField("クロム", null=False, max_digits=10, decimal_places=2)
    MO = models.DecimalField("モリブデン", null=False, max_digits=10, decimal_places=2)
    RETOL = models.DecimalField("レチノール", null=False, max_digits=10, decimal_places=2)
    CARTA = models.DecimalField("α-カロテン", null=False, max_digits=10, decimal_places=2)
    CARTB = models.DecimalField("β-カロテン", null=False, max_digits=10, decimal_places=2)
    CRYPXB = models.DecimalField("β-クリプトキサンチン", null=False, max_digits=10, decimal_places=2)
    CARTBEQ = models.DecimalField("β-カロテン当量", null=False, max_digits=10, decimal_places=2)
    VITA_RAE = models.DecimalField("レチノール活性当量", null=False, max_digits=10, decimal_places=2)
    VITD = models.DecimalField("ビタミンD", null=False, max_digits=10, decimal_places=2)
    TOCPHA = models.DecimalField("α-トコフェロール", null=False, max_digits=10, decimal_places=2)
    TOCPHB = models.DecimalField("β-トコフェロール", null=False, max_digits=10, decimal_places=2)
    TOCPHG = models.DecimalField("γ-トコフェロール", null=False, max_digits=10, decimal_places=2)
    TOCPHD = models.DecimalField("δ-トコフェロール", null=False, max_digits=10, decimal_places=2)
    VITK = models.DecimalField("ビタミンK", null=False, max_digits=10, decimal_places=2)
    THIAHCL = models.DecimalField("ビタミンB1", null=False, max_digits=10, decimal_places=2)
    RIBF = models.DecimalField("ビタミンB2", null=False, max_digits=10, decimal_places=2)
    NIA = models.DecimalField("ナイアシン", null=False, max_digits=10, decimal_places=2)
    VITB6A = models.DecimalField("ビタミンB6", null=False, max_digits=10, decimal_places=2)
    VITB12 = models.DecimalField("ビタミンB12", null=False, max_digits=10, decimal_places=2)
    FOL = models.DecimalField("葉酸", null=False, max_digits=10, decimal_places=2)
    PANTAC = models.DecimalField("パントテン酸", null=False, max_digits=10, decimal_places=2)
    BIOT = models.DecimalField("ビオチン", null=False, max_digits=10, decimal_places=2)
    VITC = models.DecimalField("ビタミンC", null=False, max_digits=10, decimal_places=2)
    NACL_EQ = models.DecimalField("食塩相当量", null=False, max_digits=10, decimal_places=2)
    ALC = models.DecimalField("アルコール", null=False, max_digits=10, decimal_places=2)
    NITRA = models.DecimalField("硝酸イオン", null=False, max_digits=10, decimal_places=2)
    THEBRN = models.DecimalField("テオブロミン", null=False, max_digits=10, decimal_places=2)
    CAFFN = models.DecimalField("カフェイン", null=False, max_digits=10, decimal_places=2)
    TAN = models.DecimalField("タンニン", null=False, max_digits=10, decimal_places=2)
    POLYPHENT = models.DecimalField("ポリフェノール", null=False, max_digits=10, decimal_places=2)
    ACEAC = models.DecimalField("酢酸", null=False, max_digits=10, decimal_places=2)
    COOKING_OIL = models.DecimalField("調理油", null=False, max_digits=10, decimal_places=2)
    OA = models.DecimalField("有機酸", null=False, max_digits=10, decimal_places=2)
    RATE_OF_CHANGE_IN_WEIGHT = models.DecimalField("重量変化率", null=False, max_digits=10, decimal_places=2)
    create_user = models.CharField("作成者", blank=False, max_length=128)
    create_datetime = models.DateTimeField(("作成日"), auto_now=False, auto_now_add=True)
    update_user = models.CharField("更新者", max_length=128)
    update_datetime = models.DateTimeField(("更新日"), auto_now=True, auto_now_add=False)
